#
# Copyright 2023 Yu Junyang
# https://github.com/lowkeyfish
#
# This file is part of IDDD.
#
# IDDD is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# IDDD is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with IDDD.
# If not, see <http://www.gnu.org/licenses/>.
#

server:
  port: 4002

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/iddd?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-init-sql: SET NAMES utf8mb4
      maximum-pool-size: 500
      minimum-idle: 1
      max-lifetime: 1800000
      connection-test-query: "select 1"
      connection-timeout: 30000
      idle-timeout: 600000
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    connect-timeout: 2000
    timeout: 5000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: iddd
    password: 123456
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30

