classDiagram
    class Activity {
        <<聚合根>>
        -ActivityId id
        -DealerId dealerId
        -String name
        -String summary
        -String image
        -TimeRange visibleTimeRange
        -TimeRange usableTimeRange
        -int participantLimit
        -List~ActivityGift~ gifts
        -ActivityStatusType status
        -boolean deleted

        +Activity(..., List&lt;ActivityGift> gifts, status, deleted)
        +Activity(..., Map&lt;GiftId, Integer> gifts)

        +udpate() void
        +start() void
        +end() void
        +register() ActivityRegistration
        +snapshot() ActivitySnapshot
    }

    class ActivityCreated {
        <<领域事件>>
    }

    class ActivityUpdated {
        <<领域事件>>
    }

    class ActivityStarted {
        <<领域事件>>
    }

    class ActivityEnded {
        <<领域事件>>
    }

    class ActivityRegistration {
        <<聚合根>>
    }

    class ActivityGift {
        <<实体>>
        -GiftId giftId
        -int count
        -int remainingCount

        +receive()
    }

    class ActivityNameUniquenessCheckService {
        <<领域服务>>
        -activityRepository
        +isNameUsed(name) boolean
        +isNameUsed(activity, name) boolean
    }

    class ActivityRepository {
        <<仓库>>
    }


    class ActivityFactory {
        <<工厂>>
        -ActivityNameUniquenessCheckService activityNameUniquenessCheckService
        +createFactory(\n&nbsp;&nbsp;Dealer dealer,\n&nbsp;&nbsp;String name,\n&nbsp;&nbsp;String summary,\n&nbsp;&nbsp;String image,\n&nbsp;&nbsp;TimeRange visibleTimeRange,\n&nbsp;&nbsp;TimeRange usableTimeRange,\n&nbsp;&nbsp;int participantLimit,\n&nbsp;&nbsp;Map&lt;Gift, Integer&gt; gifts\n): Activity
    }

    Activity ..> ActivityCreated : 构造函数
    Activity ..> ActivityUpdated : update()
    Activity ..> ActivityStarted : start()
    Activity ..> ActivityEnded : end()
    Activity ..> ActivityRegistration : register()
    Activity "1" *-- "*" ActivityGift : 活动礼品
    Activity ..> ActivityNameUniquenessCheckService: 更新活动信息时检查名称是否被占用

    ActivityRepository ..> Activity: 查询/持久化

    ActivityFactory ..> Activity: 创建活动聚合根
    ActivityFactory ..> ActivityNameUniquenessCheckService: 创建活动时检查名称是否被占用
