@startmindmap
'https://plantuml.com/mindmap-diagram

'caption figure 1
title DDD 项目结构

'* <&flag>Debian
'** <&globe>Ubuntu
'*** Linux Mint
'*** Kubuntu
'*** Lubuntu
'*** KDE Neon
'** <&graph>LMDE
'** <&pulse>SolydXK
'** <&people>SteamOS
'** <&star>Raspbian with a very long name
'*** <s>Raspmbc</s> => OSMC
'*** <s>Raspyfi</s> => Volumio


* src/main
    * <&folder> java
        * <&folder> application（应用层）
            * <&folder> command（应用服务方法参数数据类型）
            * <&folder> data（查询服务返回数据类型）
            * <&folder> event
                *_ DomainEventProcessor（使用 AOP 实现同一事务内领域事件持久化）
            * <&folder> ...
            *_ ×××ApplicationService（应用服务）
            *_ ×××QueryService（查询服务）
        * <&folder> config（项目配置）
            * <&folder> rabbitmq（RabbitMQ 配置）
            * <&folder> schedule（定时任务配置）
            * <&folder> ...
        * <&folder> controller（对外接口控制器）
        * <&folder> domain（领域层）
            * <&folder> activity
                *_ Activity（聚合根）
                *_ ActivityCreated（领域事件）
                *_ ActivityRepository（资源库接口）
                *_ ActivityNameUniquenessCheckService（领域服务）
                *_ ActivityId（聚合根标识、值对象）
                *_ ActivityGift（实体）
                *_ ...
            * <&folder> dealer
            * <&folder> ...
        * <&folder> graphql（GraphQL 配置）
        * <&folder> infrastructure（基础设施层）
            * <&folder> persistence（数据持久化）
                * <&folder> mybatis
                    * <&folder> mapper
                        *_ ×××Mapper（每个数据库表对应一个 Mapper）
                    * <&folder> model
                        *_ ×××DatabaseModel（每个数据库表对应一个 DatabaseModel）
                *_ ×××Repository（资源库实现类）
            * <&folder> remote（使用的外部接口）
                * <&folder> ×××（可以按照外部系统划分）
                    *_ ×××RequestBody（接口参数）
                    *_ ×××Response（接口响应）
                    *_ ×××Api（FeignClient）
            * <&folder> service（领域服务接口实现）
                *_ ×××Service（领域服务接口实现）
            * <&folder> ...
        * <&folder> listener（领域事件订阅）
        * <&folder> schedule（定时任务）
        * <&folder> common（通用代码和工具类，可以提出作为单独项目）
            * <&folder> data
            * <&folder> domain
            * <&folder> enums
            * <&folder> exception
            * <&folder> rabbitmq
            * <&folder> infrastructure
            * <&folder> utils
            * <&folder> ...
        * <&folder> ...

    * <&folder> resources
        * <&folder> graphql（GraphQL schema）
        * <&folder> mybatis（MyBatis XML）
        * <&folder> ...
        *_ application.yml


'header
'My super header
'endheader

'center footer My super footer

'legend right
'  Short
'  legend
'endlegend
@endmindmap
